Set the constructor of ReplayAction as public
jenkinsci/workflow-cps-plugin pull request #343
Opened 2019-12-10 00:59 UTC by LinuxSuRen

It's no harm to set the constructor as public. And I hope I can reuse ReplayAction in my plugin directly.

2020-11-26 09:02 UTC, MaciejKucia commented
Any chance to get this merged? I wanted to create plugin to prevent using Replay.

2020-11-26 10:13 UTC, MaciejKucia approved these changes
Seems live a minimum risk change

2020-11-26 10:58 UTC, LinuxSuRen commented
ping @jenkinsci/code-reviewers

2020-11-26 13:53 UTC, oleg-nenashev approved these changes
Fine with me

2020-11-30 19:10 UTC, jglick requested changes
Proposed API additions should be accompanied by downstream PRs using JEP-305 to demonstrate API usage with functional tests.

2021-01-08 16:24 UTC, bitwiseman commented
@LinuxSuRen What change did you want to make in your plugin? Please create a PR there the uses the incremental build from this PR so it is possible to see the change working.

2021-01-08 16:26 UTC, markyjackson-taulia approved these changes

2022-11-01 17:55 UTC, dwnusbaum commented
I am closing this. Feel free to resolve any merge conflicts and reopen it with a link to another PR that demonstrates the use case if you are still interested in this change.

2022-11-01 17:55 UTC, closed without merging